/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.AddForms;
import clases.Datos;
import clases.Peticiones;
import static formularios.f_principal.panel_center;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GLARA
 */
public class config extends javax.swing.JInternalFrame {

    /**
     * Variables para realizar las transacciones con la base de datos
     */
    String nombreTabla = "clientes";
    String[] titulos = {"Id", "Código", "Nombre Cliente", "Dirección", "Nit", "Limite Créd"};
    String campos = "codigo, nombre, direccion, correo, nit, telefono, fec_reg, lim_cred, estado";
    String nombreId = "idClientes";

    DefaultTableModel model;
    Datos datos = new Datos();
    Peticiones peticiones = new Peticiones();
    boolean editar = false;

    /**
     * Creates new form Config
     */
    public config() {
        initComponents();

        /**
         * Oculta la primer columna de la tala, la que contiene el Id
         */
    }

    /**
     * Prepara el formulario y jtable para crear un nuevo cliente (Habilita y
     * limpia los campos correspondientes
     */
    public void nuevo() {
//        Utilidades.setEditableTexto(this.panelFormulario, true, null, true, "");
//        //Utilidades.setEditableTexto(this.panelBusqueda, false, null, true, "");
//        Utilidades.setEditableTexto(this.panelResultados, false, null, true, "");
//        Utilidades.buscarBotones(this.panelBotonesformulario, true, null);
//        model.setRowCount(0);
//        //txtCodigo.requestFocus();
    }

    private String Validar(String x) {
        String y;
        if (x.equals("")) {
            y = "0";
            return y;
        } else {
            y = x;
            return y;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage = new elaprendiz.gui.panel.PanelImage();
        panelBusqueda = new javax.swing.JPanel();
        lbMarca = new javax.swing.JLabel();
        lbProveedor = new javax.swing.JLabel();
        lbUnidad = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelResultados = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbUsuarios = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelFormulario = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelEncabezado = new jcMousePanel.jcMousePanel();
        labelEncabezado = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        bnCrear = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("config"); // NOI18N
        setOpaque(true);

        panelImage.setBackground(new java.awt.Color(255, 255, 255));
        panelImage.setLayout(null);

        panelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBusqueda.setPreferredSize(new java.awt.Dimension(890, 82));
        panelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/category_label.png"))); // NOI18N
        lbMarca.setText("jLabel1");
        lbMarca.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbMarcaMouseMoved(evt);
            }
        });
        lbMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMarcaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMarcaMouseExited(evt);
            }
        });
        panelBusqueda.add(lbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 64, -1));

        lbProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/provider.png"))); // NOI18N
        lbProveedor.setText("jLabel1");
        lbProveedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbProveedorMouseMoved(evt);
            }
        });
        lbProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbProveedorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbProveedorMouseExited(evt);
            }
        });
        panelBusqueda.add(lbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 64, -1));

        lbUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unit.png"))); // NOI18N
        lbUnidad.setText("jLabel1");
        lbUnidad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbUnidadMouseMoved(evt);
            }
        });
        lbUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUnidadMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUnidadMouseExited(evt);
            }
        });
        panelBusqueda.add(lbUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 64, -1));

        lbCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marca.png"))); // NOI18N
        lbCategoria.setText("jLabel1");
        lbCategoria.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbCategoriaMouseMoved(evt);
            }
        });
        lbCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCategoriaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCategoriaMouseExited(evt);
            }
        });
        panelBusqueda.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 64, -1));

        jLabel1.setFont(new java.awt.Font("Decker", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nivel");
        panelBusqueda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 64, -1));

        jLabel2.setFont(new java.awt.Font("Decker", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alumno");
        panelBusqueda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Decker", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Carrera");
        panelBusqueda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 64, -1));

        jLabel4.setFont(new java.awt.Font("Decker", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ciclo");
        panelBusqueda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 64, -1));

        panelImage.add(panelBusqueda);
        panelBusqueda.setBounds(0, 88, 890, 140);

        panelResultados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelResultados.setPreferredSize(new java.awt.Dimension(786, 402));
        panelResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/category_label.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelResultados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 64, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marca.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panelResultados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 64, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notepad.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panelResultados.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 64, -1));

        lbUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user-group.png"))); // NOI18N
        lbUsuarios.setText("jLabel1");
        lbUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbUsuariosMouseMoved(evt);
            }
        });
        lbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUsuariosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUsuariosMouseExited(evt);
            }
        });
        panelResultados.add(lbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 64, -1));

        jLabel9.setFont(new java.awt.Font("Decker", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Seccion");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        panelResultados.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 64, -1));

        jLabel10.setFont(new java.awt.Font("Decker", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Usuarios");
        panelResultados.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 64, -1));

        jLabel11.setFont(new java.awt.Font("Decker", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Docente");
        jLabel11.setToolTipText("");
        panelResultados.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 64, -1));

        jLabel12.setFont(new java.awt.Font("Decker", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Grupo");
        panelResultados.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 64, -1));

        panelImage.add(panelResultados);
        panelResultados.setBounds(0, 227, 890, 140);

        panelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        panelFormulario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/provider.png"))); // NOI18N
        jLabel13.setText("jLabel1");
        panelFormulario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 64, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unit.png"))); // NOI18N
        jLabel14.setText("jLabel1");
        panelFormulario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 64, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marca.png"))); // NOI18N
        jLabel15.setText("jLabel1");
        panelFormulario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 64, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/category_label.png"))); // NOI18N
        jLabel16.setText("jLabel1");
        panelFormulario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 64, -1));

        panelImage.add(panelFormulario);
        panelFormulario.setBounds(0, 365, 890, 360);

        panelEncabezado.setColor1(new java.awt.Color(102, 153, 255));
        panelEncabezado.setColor2(new java.awt.Color(255, 255, 255));
        panelEncabezado.setModo(3);

        labelEncabezado.setFont(new java.awt.Font("Decker", 1, 17)); // NOI18N
        labelEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        labelEncabezado.setText("CONFIGURACIÓN");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addComponent(labelEncabezado)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        panelImage.add(panelEncabezado);
        panelEncabezado.setBounds(0, 0, 890, 24);

        panelBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBotones.setFocusable(false);

        bnCrear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png"))); // NOI18N
        bnCrear.setText("Crear");
        bnCrear.setToolTipText("");
        bnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bnCrear)
                .addContainerGap(793, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImage.add(panelBotones);
        panelBotones.setBounds(0, 22, 890, 68);

        getContentPane().add(panelImage, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProveedorMouseClicked
        // TODO add your handling code here:
        f_alumno newfrm = new f_alumno();
        if (newfrm == null) {
            newfrm = new f_alumno();
        }
        AddForms.adminInternalFrame(panel_center, newfrm);
    }//GEN-LAST:event_lbProveedorMouseClicked

    private void bnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCrearActionPerformed
        // TODO add your handling code here:
        editar = false;
        nuevo();
    }//GEN-LAST:event_bnCrearActionPerformed

    private void lbProveedorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProveedorMouseMoved
        // TODO add your handling code here:
        lbProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lbProveedorMouseMoved

    private void lbProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProveedorMouseExited
        // TODO add your handling code here:
        lbProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lbProveedorMouseExited

    private void lbCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCategoriaMouseClicked
        // TODO add your handling code here:
        f_cicoescolar newfrm = new f_cicoescolar();
        if (newfrm == null) {
            newfrm = new f_cicoescolar();
        }
        AddForms.adminInternalFrame(panel_center, newfrm);
    }//GEN-LAST:event_lbCategoriaMouseClicked

    private void lbUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUnidadMouseClicked
        // TODO add your handling code here:
        f_carrera newfrm = new f_carrera();
        if (newfrm == null) {
            newfrm = new f_carrera();
        }
        AddForms.adminInternalFrame(panel_center, newfrm);
    }//GEN-LAST:event_lbUnidadMouseClicked

    private void lbMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMarcaMouseClicked
        // TODO add your handling code here:
        f_nivel newfrm = new f_nivel();
        if (newfrm == null) {
            newfrm = new f_nivel();
        }
        AddForms.adminInternalFrame(panel_center, newfrm);
    }//GEN-LAST:event_lbMarcaMouseClicked

    private void lbUnidadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUnidadMouseMoved
        // TODO add your handling code here:
        lbUnidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lbUnidadMouseMoved

    private void lbCategoriaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCategoriaMouseMoved
        // TODO add your handling code here:
        lbCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lbCategoriaMouseMoved

    private void lbMarcaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMarcaMouseMoved
        // TODO add your handling code here:
        lbMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lbMarcaMouseMoved

    private void lbUnidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUnidadMouseExited
        // TODO add your handling code here:
        lbUnidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lbUnidadMouseExited

    private void lbCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCategoriaMouseExited
        // TODO add your handling code here:
        lbCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lbCategoriaMouseExited

    private void lbMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMarcaMouseExited
        // TODO add your handling code here:
        lbMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lbMarcaMouseExited

    private void lbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUsuariosMouseClicked
        // TODO add your handling code here:
        f_usuario newfrm = new f_usuario();
        if (newfrm == null) {
            newfrm = new f_usuario();
        }
        AddForms.adminInternalFrame(panel_center, newfrm);
    }//GEN-LAST:event_lbUsuariosMouseClicked

    private void lbUsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUsuariosMouseMoved
        // TODO add your handling code here:
        lbUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lbUsuariosMouseMoved

    private void lbUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUsuariosMouseExited
        // TODO add your handling code here:
        lbUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lbUsuariosMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        f_grupo newfrm = new f_grupo();
        if (newfrm == null) {
            newfrm = new f_grupo();
        }
        AddForms.adminInternalFrame(panel_center, newfrm);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         f_docente newfrm = new f_docente();
        if (newfrm == null) {
            newfrm = new f_docente();
        }
        AddForms.adminInternalFrame(panel_center, newfrm);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         f_seccion newfrm = new f_seccion();
        if (newfrm == null) {
            newfrm = new f_seccion();
        }
        AddForms.adminInternalFrame(panel_center, newfrm);
              
    }//GEN-LAST:event_jLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelEncabezado;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbProveedor;
    private javax.swing.JLabel lbUnidad;
    private javax.swing.JLabel lbUsuarios;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBusqueda;
    private jcMousePanel.jcMousePanel panelEncabezado;
    private javax.swing.JPanel panelFormulario;
    private elaprendiz.gui.panel.PanelImage panelImage;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables
}
